server:
  port: 8090


spring:
  datasource:
      url: "jdbc:mysql://db9052.public.databaseasp.net:3306/db9052"
      username: db9052
      password: 3i#Z+Lb9E7-e
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true