server:
  port: 8090


spring:
  datasource:
      url: "jdbc:mysql://${DATABASE_HOST:db9052.public.databaseasp.net}:${DATABSE_PORT:3306}/${DATABASE_NAME:db9052}"
      username: ${DATABASE_USER:db9052}
      password: ${DATABASE_PASSWORD:3i#Z+Lb9E7-e}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true