//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CNPM_Community_support.Module.ORMDataModel1
{

    public partial class Bieumau : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fDiadiem;
        public string Diadiem
        {
            get { return fDiadiem; }
            set { SetPropertyValue<string>(nameof(Diadiem), ref fDiadiem, value); }
        }
        string fMota;
        [Size(SizeAttribute.Unlimited)]
        public string Mota
        {
            get { return fMota; }
            set { SetPropertyValue<string>(nameof(Mota), ref fMota, value); }
        }
        string fSdt;
        [Size(12)]
        public string Sdt
        {
            get { return fSdt; }
            set { SetPropertyValue<string>(nameof(Sdt), ref fSdt, value); }
        }
        DateTime fNgayghinhan;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime Ngayghinhan
        {
            get { return fNgayghinhan; }
            set { SetPropertyValue<DateTime>(nameof(Ngayghinhan), ref fNgayghinhan, value); }
        }
        string fGhichu;
        [Size(SizeAttribute.Unlimited)]
        public string Ghichu
        {
            get { return fGhichu; }
            set { SetPropertyValue<string>(nameof(Ghichu), ref fGhichu, value); }
        }
        string fNoidungchi;
        [Size(SizeAttribute.Unlimited)]
        public string Noidungchi
        {
            get { return fNoidungchi; }
            set { SetPropertyValue<string>(nameof(Noidungchi), ref fNoidungchi, value); }
        }
        DateTime fThoigianchi;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime Thoigianchi
        {
            get { return fThoigianchi; }
            set { SetPropertyValue<DateTime>(nameof(Thoigianchi), ref fThoigianchi, value); }
        }
        decimal fTienchi;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal Tienchi
        {
            get { return fTienchi; }
            set { SetPropertyValue<decimal>(nameof(Tienchi), ref fTienchi, value); }
        }
        Danhmuc fDanhmucID;
        [Association(@"BieumauReferencesDanhmuc")]
        public Danhmuc DanhmucID
        {
            get { return fDanhmucID; }
            set { SetPropertyValue<Danhmuc>(nameof(DanhmucID), ref fDanhmucID, value); }
        }
        User fUserID;
        [Association(@"BieumauReferencesUser")]
        public User UserID
        {
            get { return fUserID; }
            set { SetPropertyValue<User>(nameof(UserID), ref fUserID, value); }
        }
        Tochuc fTochucID;
        [Association(@"BieumauReferencesTochuc")]
        public Tochuc TochucID
        {
            get { return fTochucID; }
            set { SetPropertyValue<Tochuc>(nameof(TochucID), ref fTochucID, value); }
        }
        short fisBieumautam;
        public short isBieumautam
        {
            get { return fisBieumautam; }
            set { SetPropertyValue<short>(nameof(isBieumautam), ref fisBieumautam, value); }
        }
        [Association(@"HinhanhReferencesBieumau"), Aggregated]
        public XPCollection<Hinhanh> Hinhanhs { get { return GetCollection<Hinhanh>(nameof(Hinhanhs)); } }
        [Association(@"QuyengopReferencesBieumau"), Aggregated]
        public XPCollection<Quyengop> Quyengops { get { return GetCollection<Quyengop>(nameof(Quyengops)); } }
    }

}
