//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CNPM_Community_support.Module.ORMDataModel1
{

    [DefaultProperty("Tendanhmuc")]
    public partial class Danhmuc : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fTendanhmuc;
        [Size(25)]
        public string Tendanhmuc
        {
            get { return fTendanhmuc; }
            set { SetPropertyValue<string>(nameof(Tendanhmuc), ref fTendanhmuc, value); }
        }
        [Association(@"BieumauReferencesDanhmuc"), Aggregated]
        public XPCollection<Bieumau> Bieumaus { get { return GetCollection<Bieumau>(nameof(Bieumaus)); } }
    }

}
