//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CNPM_Community_support.Module.ORMDataModel1
{

    public partial class Hinhanh : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fPath;
        [Size(SizeAttribute.Unlimited)]
        public string Path
        {
            get { return fPath; }
            set { SetPropertyValue<string>(nameof(Path), ref fPath, value); }
        }
        Bieumau fBieumauID;
        [Association(@"HinhanhReferencesBieumau")]
        public Bieumau BieumauID
        {
            get { return fBieumauID; }
            set { SetPropertyValue<Bieumau>(nameof(BieumauID), ref fBieumauID, value); }
        }
    }

}
