//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CNPM_Community_support.Module.ORMDataModel1
{

    [DefaultProperty("Nguoidaidien")]
    public partial class Tochuc : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fNguoidaidien;
        [Size(50)]
        public string Nguoidaidien
        {
            get { return fNguoidaidien; }
            set { SetPropertyValue<string>(nameof(Nguoidaidien), ref fNguoidaidien, value); }
        }
        string fSdt;
        [Size(12)]
        public string Sdt
        {
            get { return fSdt; }
            set { SetPropertyValue<string>(nameof(Sdt), ref fSdt, value); }
        }
        string fPassword;
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        string fCCCD;
        [Size(12)]
        public string CCCD
        {
            get { return fCCCD; }
            set { SetPropertyValue<string>(nameof(CCCD), ref fCCCD, value); }
        }
        string fTentochuc;
        public string Tentochuc
        {
            get { return fTentochuc; }
            set { SetPropertyValue<string>(nameof(Tentochuc), ref fTentochuc, value); }
        }
        string fDiachi;
        public string Diachi
        {
            get { return fDiachi; }
            set { SetPropertyValue<string>(nameof(Diachi), ref fDiachi, value); }
        }
        string fMota;
        [Size(SizeAttribute.Unlimited)]
        public string Mota
        {
            get { return fMota; }
            set { SetPropertyValue<string>(nameof(Mota), ref fMota, value); }
        }
        [Association(@"BieumauReferencesTochuc"), Aggregated]
        public XPCollection<Bieumau> Bieumaus { get { return GetCollection<Bieumau>(nameof(Bieumaus)); } }
    }

}
